config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get  'home/about'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many_attached :uploads

    




end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pins 
  has_one_attached :avatar
  has_many_attached :image 
  has_many_attached :uploads     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :html

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
    respond_with(@pin)
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit 
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params) 
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    if @pin.update(pin_params)
       redirect_to @pin, notice: 'Pin was successfully updated.'
     else
       render action: 'edit'
     end
   end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description, :image, uploads: [])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TIGSE', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">   


    <ul class="nav navbar-nav navbar-right">

      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'About Us', home_about_path %></li>
      <li><%= link_to "List Pins", pins_path %></li>
      
      <% if user_signed_in? %>
        <li><%= link_to "Add Pin", new_pin_path %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
         <li> <%= link_to "Edit Profile", edit_user_registration_path %> </li>
      <% else %>

        <li><%= link_to "Login",  new_user_session_url %></li>

        <li><%= link_to "Join",  new_user_registration_url %></li>

      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>

app/views/home/about.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2>About Us</h2></div>
<div class="panel-body">


<p> Tigse - a tibetan word for proportion.</p>

</div>
<div class= "panel-footer"> </div>
</div>

app/views/home/index.html.erb
    <div class="jumbotron">
        <div class="row align-items-start">
            <div class="col">
            <%= image_tag("Logo_lrg_06.jpg", :alt => "logo") %>
            </div>
        </div>
     </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tigse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'home/header' %>

  <div class="container">

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>

    <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

<div class="form-group">
          <% if pin.image.attached? %>
            <%= image_tag pin.image, style: "width: 200px; display: block" %>
          <% end %>
  </div>

  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class='form-group'>
  <%= f.label :uploads %>
  <%= f.file_field :uploads, multiple: true, class: "form-control" %>
</div>
  
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2>Edit Pin</h2></div>
    <div class="panel-body">

<%= render 'form', pin: @pin %>

</div>

<div class= "panel-footer"><%= link_to 'Show', @pin %> | <%= link_to 'Back', pins_path %> </div>

</div>

app/views/pins/index.html.erb
<div id='pins' class="transitions-enabled">
        <% @pins.each do |pin| %>

          <div class="box">

            <%= link_to image_tag(pin.image, class: 'w-100', style: 'max-width: 20rem;'), pin %><br/>
            <%= pin.description %>  <br/>

           <% if pin.user == current_user %>

            <%= link_to 'Edit', edit_pin_path(pin) %> |
            <%= link_to 'Delete', pin, method: :delete,  data: { confirm: 'Are you sure?' } %>

        <% end %>
        <br>
        </div>
      <% end %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
<div class="panel-heading"><h2>New Pin</h2></div>
    <div class="panel-body">


    <%= render 'form', pin: @pin %>
   


    </div>

 <div class= "panel-footer"> <%= link_to 'Back', pins_path %> </div>

</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
    <div class="panel-heading"><p>
    <strong>Description:</strong>
    <%= @pin.description %>
    </p>
    </div>
 
 <div class="panel-body">
      <div style:'width: 200px; height: auto'>
        <%= image_tag(@pin.image) %>
  </div>
</div>

<div class= "panel-footer"> 

      <%= link_to 'Edit', edit_pin_path(@pin) %> | <%= link_to 'Back', pins_path %>

      <h5> Download the PDF: </h5>

        <td style="text-align:left">
          <% @pin.uploads.each do |upload| %>
            <% if upload.variable? %>
              <%= link_to image_tag(upload.variant), upload %>
            <% else %>
              <%= link_to upload.filename, upload %>
            <% end %>
          <% end %>
        </td>




</div>